# -*- coding: utf-8 -*-

import unittest

from test_case.test_login import TestLogin
from utils.HTMLTestRunner import HTMLTestRunner
from utils.mail import Email

if __name__ == '__main__':
	suite = unittest.defaultTestLoader.discover('D:/python/unittest/oa_test/test_case', pattern='test_*.py')
	with open('./report/HTMLReport.html', 'w') as f:
		runner = HTMLTestRunner(stream=f,
								title='OA Test Report',
								description='generated by HTMLTestRunner.',
								verbosity=2)
		runner.run(suite)
	e = Email('smtp.grgbanking.com','xjming9@grgbanking.com','grg7792042','13250790293@163.com','success')
	e.send()