var = {"code": 0, "message": "成功", "content": {
    "orderInfo": {"orderId": "6771233083610890346", "productTypeId": "2", "businessType": 0, "carTypeId": "1",
                  "carTypeIds": "1", "carTypeName": "经济型", "source": 0, "platform": 3, "status": 9, "statusRc": 0,
                  "statusMapSync": 6, "statusForceEnd": 0, "statusAbnormal": 0, "statusDispatch": 0, "flag": "0",
                  "userAccountId": "0", "userId": "1682389398", "userPhone": "15989104405", "userName": "",
                  "userCompanyId": "0", "userCompanyDeptId": "0", "userFlightNumber": "", "carId": "80801522",
                  "rentCompanyId": 608, "carModel": "甲壳虫", "carModelId": "0", "carBrand": "广汽传褀2",
                  "carNumber": "粤A58118", "carColor": 1, "driverId": "6834282", "driverPhone": "13250790293",
                  "driverName": "大师傅", "dispatchTimeLength": 0, "timeInit": "1576550557", "timeDispatchStart": "0",
                  "timeDispatchDone": "1576550576", "timeArrival": "1576550590", "timeStart": "1576550592",
                  "timeEnd": "1576550596", "timeConfirm": "1576550601", "timeCancel": "0", "timeRefund": "1576565227",
                  "timeRefundCoupon": "1576561576", "couponId": "6771231678353310147",
                  "refundCouponId": "6771231678353310147", "refundAmount": 10.00, "timeAccept": "1576550573",
                  "expectStartTime": "1576554629", "expectEndTime": "1576556309", "startLatitude": 23.1074,
                  "startLongitude": 113.33599, "startCity": "440100", "startCityName": "广州市",
                  "startPosition": "广报中心-西北门", "startAddress": "广报中心-西北门", "startPoiid": "",
                  "endLatitude": 22.988558425, "endLongitude": 113.269322777, "endCity": "440100", "endCityName": "广州",
                  "endPosition": "广州南站", "endAddress": "广东省广州市番禺区石壁街", "endPoiid": "5590598431056816962",
                  "cancelSource": 0, "cancelReasonId": "0", "cancelAmount": 0.00, "otherCancelReason": "",
                  "cancelBeforeStatus": 0, "realStartLatitude": 23.10686550564236,
                  "realStartLongitude": 113.3362556966146, "realEndLatitude": 23.10686550564236,
                  "realEndLongitude": 113.3362556966146, "discount": 10.00, "driverHighwayAmount": 0.00,
                  "driverParkingAmount": 10.00, "driverBridgeAmount": 0.00, "driverTipAmount": 0.00,
                  "driverOtherAmount": 0.00, "driverOtherAmountReason": "", "driverInputDistance": 0.00,
                  "driverInputRuntime": "0", "clientSystemDistance": 0.00, "chargeTimeLength": 0,
                  "chargeDistance": 0.00, "chargeLongDistance": 0.00, "chargeTimeAmount": 0.00,
                  "chargeDistanceAmount": 0.00, "chargeLongDistanceAmount": 0.00, "chargeTotalAmount": 10.05,
                  "chargeOriginTotalAmount": 10.05, "chargeDriverAmount": 0.00, "chargeOriginDriverAmount": 0.00,
                  "payChannel": 1, "payDoneAmount": 10.00, "payLeftAmount": 0.00, "invoiceAmount": 0.00,
                  "payMinAmount": 0.00, "payPreMethod": 1, "payPreChannel": 1, "payPreAuthStatus": 2,
                  "payPreCredit": 2.03, "payFirstTransactionId": "0", "payFirstAmount": 0.00, "payAllow": 1,
                  "statusPay": 3, "statusRefund": 3, "statusSettlement": 0, "statusInvoice": 0, "statusComment": 0,
                  "operator": "", "createTime": "2019-12-17 10:42:49", "updateTime": "2019-12-17 14:47:07",
                  "timePay": "1576550611", "startAdCode": "440105", "endAdCode": "440113", "couponAmount": 0.05,
                  "discountAmount": 0.00, "pointEndLatitude": 23.107405, "pointEndLongitude": 113.335987},
    "couponCheck": {"orderId": "6771233083610890346", "couponId": "6771231678353310147"}, "orderRefundRecords": [
        {"refundId": "1052", "accountId": "200003539", "orderId": "6771233083610890346",
         "tradeNo": "2000035391576550557761", "channel": 1, "source": 1, "refundAmount": 203, "refundBaseAmount": 0,
         "refundExtraAmount": 203, "comment": "网页脚本退款", "extra": "退款成功", "refundSign": 0, "operator": "gactravel1",
         "createTime": "1576565227000", "updateTime": "1576565227000"},
        {"refundId": "1051", "accountId": "200003539", "orderId": "6771233083610890346",
         "tradeNo": "2000035391576550602062", "channel": 1, "source": 1, "refundAmount": 697, "refundBaseAmount": 0,
         "refundExtraAmount": 697, "comment": "网页脚本退款", "extra": "退款成功", "refundSign": 0, "operator": "gactravel1",
         "createTime": "1576565225000", "updateTime": "1576565225000"},
        {"refundId": "1049", "accountId": "200003539", "orderId": "6771233083610890346",
         "tradeNo": "2000035391576550602062", "channel": 1, "source": 1, "refundAmount": 100, "refundBaseAmount": 0,
         "refundExtraAmount": 100, "comment": "1", "extra": "退款成功", "refundSign": 0, "operator": "gactravel1",
         "createTime": "1576561569000", "updateTime": "1576561569000"}],
    "chargeSnapshot": {"orderId": "6771233083610890346", "userType": 1, "formula": null,
                       "chargeData": {"bridgeAmount": "0", "highwayAmount": "0", "orderId": "6771233083610890346",
                                      "city": "440100", "cancelAmount": "0", "fromLat": 23.1074, "discount": "0",
                                      "fromLng": 113.33599, "createOrderTime": 1576550557, "carTypeIds": [],
                                      "chargeDriverActionType": 2, "startTime": 1576550592, "productType": 2,
                                      "orderSource": 0, "tipAmount": "0", "carTypeId": 1, "addPrice": "0",
                                      "payPreCreditAmount": "0", "userId": "1682389398", "carId": 80801522,
                                      "parkingAmount": "10", "otherAmount": "0", "toLat": 22.988558425,
                                      "estimateType": 0, "limitAmount": "0",
                                      "_class": "com.tencent.travel.charge.model.ChargeData", "userType": 1,
                                      "endTime": 1576550596, "toLng": 113.269322777}, "couponData": null,
                       "chargePrice": null,
                       "chargeResult": {"startAmount": 0.05, "feeMin": 0.02, "feeMinFlag": 2, "startDistance": 5.0,
                                        "startTimeLength": 10, "timeLength": 0, "distance": 0.00, "chargeTimeLength": 0,
                                        "chargeDistance": 0.00, "longDistance": 0, "timeAmount": 0.00,
                                        "distanceAmount": 0.00, "longDistanceAmount": 0, "highwayAmount": 0.00,
                                        "parkingAmount": 10.00, "bridgeAmount": 0.00, "tipAmount": 0.00,
                                        "otherAmount": 0.00, "addPrice": 0, "discount": 10.00, "discountMaxFee": 100.00,
                                        "basicAmount": 0.05, "originTotalAmount": 10.05, "couponAmount": 0.05,
                                        "discountAmount": 0.00, "totalAmount": 10.00, "userTotalAmount": 10.00,
                                        "beforeAdjustmentUserAmount": 0, "payPreCreditAmount": 0, "cancelAmount": 0,
                                        "couponData": {"couponId": "6771231678353310147", "couponRuleId": "456456809",
                                                       "couponBatchId": "6770865678420214211", "couponName": "奖励劵--条件",
                                                       "couponType": 2, "couponValue": 100, "limitAmount": 0.00,
                                                       "limitField": "", "limitDiscount": 0.00, "status": 1,
                                                       "startTime": "1576080000", "endTime": "1607788799"},
                                        "segPriceInfoMap": {"0-0": {"isSegment": true, "startTime": "0", "endTime": "0",
                                                                    "actualStartTime": "", "actualEndTime": "",
                                                                    "feePerMinute": 0.05, "feePerKilometer": 0.05,
                                                                    "timeLength": 0, "distance": 0, "timeAmount": 0.00,
                                                                    "distanceAmount": 0.00, "feeStart": 0,
                                                                    "commonSegmentKey": "0-0", "segmentName": "平峰"}},
                                        "longDistanceList": [], "addFeeStart": 0, "distanceBeforeMakeUp": -3},
                       "createTime": "576550597", "updateTime": null,
                       "chargePriceInfo": {"chargePkgId": "199", "chargePriceId": "199", "title": "模拟正式预约单-2",
                                           "status": 1, "city": "440100", "userType": 1, "productTypeId": 2,
                                           "carTypeId": 1, "feeStart": 0.05, "feePerMinute": 0.05,
                                           "feePerKilometer": 0.05, "freeDistance": 5.0, "freeTime": 10,
                                           "orderId": "6771233083610890346", "segPriceInfoMap": {
                               "23:00-00:00": {"chargePriceId": 199, "title": "夜间", "isSegment": 1,
                                               "segmentTimeStart": "23:00", "segmentTimeEnd": "00:00",
                                               "feePerMinute": 0.05, "feePerKilometer": 0.05, "discount": 10.0,
                                               "discountMaxFee": 40.0},
                               "00:00-05:00": {"chargePriceId": 199, "title": "夜间", "isSegment": 1,
                                               "segmentTimeStart": "00:00", "segmentTimeEnd": "05:00",
                                               "feePerMinute": 0.05, "feePerKilometer": 0.05, "discount": 10.0,
                                               "discountMaxFee": 40.0},
                               "0-0": {"chargePriceId": 199, "title": "平峰", "isSegment": 1, "feePerMinute": 0.05,
                                       "feePerKilometer": 0.05, "discount": 10.0, "discountMaxFee": 100.0}},
                                           "longDistanceList": [{"longDistancePriceId": "520", "chargePkgId": "199",
                                                                 "feeLongPerKilometer": 0.05, "freeLongDistance": 15.0,
                                                                 "status": 1, "founder": "gactravel",
                                                                 "modifier": "gactravel",
                                                                 "createTime": "2019-12-16 15:35:13",
                                                                 "updateTime": "2019-12-16 15:35:13"}],
                                           "discountInfoVoMap": {"23:00-00:00": {"discountId": "80", "segmentId": "4",
                                                                                 "discountBasicId": "29",
                                                                                 "discount": 10.0,
                                                                                 "discountMaxFee": 40.0,
                                                                                 "founder": "gactravel",
                                                                                 "modifier": "gactravel",
                                                                                 "createTime": "2019-08-29 11:08:15",
                                                                                 "updateTime": "2019-11-27 12:51:17",
                                                                                 "segmentName": "夜间", "segmentType": 0,
                                                                                 "cityName": "广州", "cityCode": "440100",
                                                                                 "startTime": "23:00",
                                                                                 "endTime": "00:00"},
                                                                 "00:00-05:00": {"discountId": "80", "segmentId": "4",
                                                                                 "discountBasicId": "29",
                                                                                 "discount": 10.0,
                                                                                 "discountMaxFee": 40.0,
                                                                                 "founder": "gactravel",
                                                                                 "modifier": "gactravel",
                                                                                 "createTime": "2019-08-29 11:08:15",
                                                                                 "updateTime": "2019-11-27 12:51:17",
                                                                                 "segmentName": "夜间", "segmentType": 0,
                                                                                 "cityName": "广州", "cityCode": "440100",
                                                                                 "startTime": "00:00",
                                                                                 "endTime": "05:00"},
                                                                 "07:00-10:00": {"discountId": "77", "segmentId": "1",
                                                                                 "discountBasicId": "29",
                                                                                 "discount": 10.0,
                                                                                 "discountMaxFee": 99.0,
                                                                                 "founder": "gactravel",
                                                                                 "modifier": "gactravel",
                                                                                 "createTime": "2019-08-29 11:08:15",
                                                                                 "updateTime": "2019-11-27 12:51:17",
                                                                                 "segmentName": "早高峰7-10",
                                                                                 "segmentType": 0, "cityName": "广州",
                                                                                 "cityCode": "440100",
                                                                                 "startTime": "07:00",
                                                                                 "endTime": "10:00"},
                                                                 "16:41-17:35": {"discountId": "82", "segmentId": "3",
                                                                                 "discountBasicId": "29",
                                                                                 "discount": 10.0,
                                                                                 "discountMaxFee": 40.0,
                                                                                 "founder": "gactravel",
                                                                                 "modifier": "gactravel",
                                                                                 "createTime": "2019-08-29 11:08:15",
                                                                                 "updateTime": "2019-11-27 12:51:17",
                                                                                 "segmentName": "16-19（暂不使用）",
                                                                                 "segmentType": 0, "cityName": "广州",
                                                                                 "cityCode": "440100",
                                                                                 "startTime": "16:41",
                                                                                 "endTime": "17:35"},
                                                                 "0-0": {"discountId": "76", "segmentId": "5",
                                                                         "discountBasicId": "29", "discount": 10.0,
                                                                         "discountMaxFee": 100.0,
                                                                         "founder": "gactravel",
                                                                         "modifier": "gactravel",
                                                                         "createTime": "2019-08-29 11:08:15",
                                                                         "updateTime": "2019-11-27 12:51:17",
                                                                         "segmentName": "平峰", "segmentType": 0,
                                                                         "cityName": "广州", "cityCode": "440100"},
                                                                 "11:25-14:00": {"discountId": "138", "segmentId": "22",
                                                                                 "discountBasicId": "29",
                                                                                 "discount": 10.0,
                                                                                 "discountMaxFee": 22.0,
                                                                                 "founder": "gactravel",
                                                                                 "modifier": "gactravel",
                                                                                 "createTime": "2019-11-13 10:04:25",
                                                                                 "updateTime": "2019-11-27 12:51:17",
                                                                                 "segmentName": "恒大", "segmentType": 0,
                                                                                 "cityName": "广州", "cityCode": "440100",
                                                                                 "startTime": "11:25",
                                                                                 "endTime": "14:00"},
                                                                 "17:50-19:00": {"discountId": "78", "segmentId": "16",
                                                                                 "discountBasicId": "29",
                                                                                 "discount": 10.0,
                                                                                 "discountMaxFee": 20.0,
                                                                                 "founder": "gactravel",
                                                                                 "modifier": "gactravel",
                                                                                 "createTime": "2019-08-29 11:08:15",
                                                                                 "updateTime": "2019-11-27 12:51:17",
                                                                                 "segmentName": "晚高峰16-19",
                                                                                 "segmentType": 0, "cityName": "广州",
                                                                                 "cityCode": "440100",
                                                                                 "startTime": "17:50",
                                                                                 "endTime": "19:00"},
                                                                 "11:00-16:00": {"discountId": "139", "segmentId": "32",
                                                                                 "discountBasicId": "29",
                                                                                 "discount": 10.0,
                                                                                 "discountMaxFee": 22.0,
                                                                                 "founder": "gactravel",
                                                                                 "modifier": "gactravel",
                                                                                 "createTime": "2019-11-13 10:04:25",
                                                                                 "updateTime": "2019-11-27 12:51:17",
                                                                                 "segmentName": "中午高峰期",
                                                                                 "segmentType": 0, "cityName": "广州",
                                                                                 "cityCode": "440100",
                                                                                 "startTime": "11:00",
                                                                                 "endTime": "16:00"},
                                                                 "20:22-23:00": {"discountId": "79", "segmentId": "2",
                                                                                 "discountBasicId": "29",
                                                                                 "discount": 10.0,
                                                                                 "discountMaxFee": 40.0,
                                                                                 "founder": "gactravel",
                                                                                 "modifier": "gactravel",
                                                                                 "createTime": "2019-08-29 11:08:15",
                                                                                 "updateTime": "2019-11-27 12:51:17",
                                                                                 "segmentName": "晚上", "segmentType": 0,
                                                                                 "cityName": "广州", "cityCode": "440100",
                                                                                 "startTime": "20:22",
                                                                                 "endTime": "23:00"},
                                                                 "05:00-06:00": {"discountId": "81", "segmentId": "17",
                                                                                 "discountBasicId": "29",
                                                                                 "discount": 10.0,
                                                                                 "discountMaxFee": 40.0,
                                                                                 "founder": "gactravel",
                                                                                 "modifier": "gactravel",
                                                                                 "createTime": "2019-08-29 11:08:15",
                                                                                 "updateTime": "2019-11-27 12:51:17",
                                                                                 "segmentName": "5-6", "segmentType": 0,
                                                                                 "cityName": "广州", "cityCode": "440100",
                                                                                 "startTime": "05:00",
                                                                                 "endTime": "06:00"}}},
                       "estimateSnapData": {"estimateId": "6771233134346174472", "orderId": "6771233083610890346",
                                            "createTime": "1576550569", "estimateInfo": {
                               "1": {"startAmount": 0.05, "feeMin": 0.02, "feeMinFlag": 2, "startDistance": 5.0,
                                     "startTimeLength": 10, "timeLength": 28, "distance": 20.72, "chargeTimeLength": 18,
                                     "chargeDistance": 15.71, "longDistance": 5.72, "timeAmount": 0.9,
                                     "distanceAmount": 0.79, "longDistanceAmount": 0.29, "highwayAmount": 0.0,
                                     "parkingAmount": 0.0, "bridgeAmount": 0.0, "tipAmount": 0.0, "otherAmount": 0.0,
                                     "addPrice": 0, "discount": 10.0, "discountMaxFee": 100.0, "basicAmount": 2.03,
                                     "originTotalAmount": 2.03, "couponAmount": 2.03, "discountAmount": 0.0,
                                     "totalAmount": 0.0, "userTotalAmount": 0.0, "beforeAdjustmentUserAmount": 0,
                                     "payPreCreditAmount": 0, "cancelAmount": 0,
                                     "couponData": {"couponId": "6771231678353310147", "couponRuleId": "456456809",
                                                    "couponBatchId": "6770865678420214211", "couponName": "奖励劵--条件",
                                                    "couponType": 2, "couponValue": 100, "limitAmount": 0.0,
                                                    "limitField": "", "limitDiscount": 0.0, "status": 0,
                                                    "startTime": "1576080000", "endTime": "1607788799"},
                                     "segPriceInfoMap": {"0-0": {"isSegment": true, "startTime": "0", "endTime": "0",
                                                                 "actualStartTime": "", "actualEndTime": "",
                                                                 "feePerMinute": 0.05, "feePerKilometer": 0.05,
                                                                 "timeLength": 18, "distance": 15.71, "timeAmount": 0.9,
                                                                 "distanceAmount": 0.79, "feeStart": 0.05,
                                                                 "commonSegmentKey": "0-0", "segmentName": "平峰"}},
                                     "longDistanceList": [{"feeLongPerKilometer": 0.05, "freeLongDistance": 15.0,
                                                           "actualLongDistance": 5.72, "actualAmount": 0.29}],
                                     "addFeeStart": 0.05}}}, "adjustmentTimes": 0, "adjustmentLimitTimes": -1,
                       "payPreCreditAmount": 2.03},
    "orderInfoExt": {"createOrderPosition": "广州报业文化中心", "createOrderAddress": "广东省广州市海珠区阅江西路",
                     "createOrderLongitude": 113.3362556966146, "createOrderLatitude": 23.10686550564236,
                     "confirmLatitude": 23.10686550564236, "confirmLongitude": 113.3362556966146,
                     "arriveLatitude": 23.10686550564236, "arriveLongitude": 113.3362556966146, "dispatchDriverIds": "",
                     "changeDriverReasonId": "0", "adjustPassengerAmount": 0.00, "adjustDriverAmount": 0.00,
                     "adjustPassengerReason": "", "adjustDriverReason": "", "adjustAmount": 0.00,
                     "estimateSnap": "{\"carModelId\":\"1\",\"custName\":\"\",\"deviceId\":\"3D3DE7CC-816A-4865-86C4-5A51C2E2ACA0\",\"deviceType\":\"iPhone8,2\",\"dispatchDuration\":false,\"estimatedKm\":\"0\",\"estimatedTime\":\"0\",\"expectStartTime\":1576554629,\"fromAdCode\":\"440105\",\"fromAddDtl\":\"广报中心-西北门\",\"fromAddress\":\"广报中心-西北门\",\"fromCityCode\":\"440100\",\"fromCityName\":\"广州市\",\"fromLat\":23.1074,\"fromLng\":113.33599,\"imei\":\"3D3DE7CC-816A-4865-86C4-5A51C2E2ACA0\",\"imsi\":\"46001\",\"mac\":\"3D3DE7CC-816A-4865-86C4-5A51C2E2ACA0\",\"orderSource\":0,\"platform\":\"iOS\",\"pointEndLatitude\":23.107405,\"pointEndLongitude\":113.335987,\"priorityContact\":0,\"prodType\":\"2\",\"submitAddDtl\":\"广东省广州市海珠区阅江西路\",\"submitAddress\":\"广州报业文化中心\",\"submitLat\":23.10686550564236,\"submitLng\":113.3362556966146,\"timestamp\":1576550555920,\"toAdCode\":\"440113\",\"toAddDtl\":\"广东省广州市番禺区石壁街\",\"toAddress\":\"广州南站\",\"toCityCode\":\"440100\",\"toCityName\":\"广州\",\"toLat\":22.988558425,\"toLng\":113.269322777,\"toPoiId\":\"5590598431056816962\",\"token\":\"AAAAEFBR9ayZj8d98Lp26PXvJElfPx6rEHQzSbXT4z7nfMYiz4gS7pVp9RaFupuSWDZOGfZ4TpMvSY3_1ddV_NKB6QTeoHc4O7NNLpltqo33-0QwcmBYcs4n0yLcoPmIXTGqV_2cSrL43BJZ7dg5x8QoioEtRWZ1vHSy9KSDCOtvvTRfsXxYexgqYnuvmeRi8C-syaYbTFsq9_BsAZ865Jyf8o1O5o2s6LY1fyBCzcmxpdSDKsExjReGUb8xDVz0f0p_55nNpDS-9D8QAn13y9y_qZZLtZlbe5zWTr_Q6yYIcLF7sNoor7EB9RNBXCmuw3ElXTvv76AksJ9DZOijQOQEpr3IpF3Wo5g=\",\"type\":\"0\",\"version\":\"200000180\"}",
                     "estimateBasicAmount": 2.03, "estimateOriginTotalAmount": 2.03, "estimateTotalAmount": 0.00,
                     "estimateDistance": 20.72, "estimateCostTime": 28, "estimateDriverAmount": 0.00,
                     "pickEstimateDistance": 1.00, "pickEstimateCostTime": 60}, "showBalanceAmount": 0.00,
    "showBaseAmount": 0.00, "showExtraAmount": 0.00,
    "payRecords": [{"payAmount": 2.03, "payStatus": 2, "channel": 1, "recordTime": "1576550568"},
                   {"payAmount": 7.97, "payStatus": 2, "channel": 1, "recordTime": "1576550611"},
                   {"payAmount": 1.0, "payStatus": 3, "channel": 1, "recordTime": "1576561569"},
                   {"payAmount": 6.97, "payStatus": 3, "channel": 1, "recordTime": "1576565225"},
                   {"payAmount": 2.03, "payStatus": 3, "channel": 1, "recordTime": "1576565226"}]}}