# -*- coding: utf-8 -*-

import unittest

from test_case.testbyrequests import TestEc
from utils.HTMLTestRunner import HTMLTestRunner
from utils.mail import Email

if __name__ == '__main__':
	suite = unittest.TestSuite()
	suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestEc))
	
	with open('./report/HTMLReport.html', 'w') as f:
		runner = HTMLTestRunner(stream=f,
								title='ErrCode_Web Test Report',
								description='generated by HTMLTestRunner.',
								verbosity=2
								)
		runner.run(suite)
	e = Email('smtp.qq.com','981805032@qq.com','nmfavcrgtlfsbdeb','13250790293@163.com','errcode网页测试')
	e.send()