# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1124, 889)
        Form.setAutoFillBackground(False)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 1101, 831))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 1081, 801))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 5, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 4, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 4, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 7, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 8, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 7, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 6, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 7, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 7, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 7, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 7, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 4, 8, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 7, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_2.setAcceptDrops(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout.addWidget(self.pushButton_29, 8, 4, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 3, 2, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout.addWidget(self.pushButton_28, 8, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 6, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 3, 6, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 7, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout.addWidget(self.pushButton_30, 8, 5, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 3, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 5, 5, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 5, 6, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 5, 4, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout.addWidget(self.pushButton_27, 8, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 5, 0, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout.addWidget(self.pushButton_26, 8, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 5, 8, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 3, 8, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout.addWidget(self.pushButton_33, 8, 8, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout.addWidget(self.pushButton_32, 8, 7, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout.addWidget(self.pushButton_31, 8, 6, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 5, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 3, 5, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 5, 7, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 5, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 4, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 5, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 7, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 8, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 7, 7, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 7, 8, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(400, 10, 261, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(20, 10, 271, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.splitter)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(Form.copy)
        self.pushButton_3.clicked.connect(Form.copy)
        self.pushButton_4.clicked.connect(Form.copy)
        self.pushButton_5.clicked.connect(Form.copy)
        self.pushButton_6.clicked.connect(Form.copy)
        self.pushButton_7.clicked.connect(Form.copy)
        self.pushButton_8.clicked.connect(Form.copy)
        self.pushButton_9.clicked.connect(Form.copy)
        self.pushButton_10.clicked.connect(Form.copy)
        self.pushButton_11.clicked.connect(Form.copy)
        self.pushButton_12.clicked.connect(Form.copy)
        self.pushButton_13.clicked.connect(Form.copy)
        self.pushButton_14.clicked.connect(Form.copy)
        self.pushButton_15.clicked.connect(Form.copy)
        self.pushButton_16.clicked.connect(Form.copy)
        self.pushButton_17.clicked.connect(Form.copy)
        self.pushButton_18.clicked.connect(Form.copy)
        self.pushButton_19.clicked.connect(Form.copy)
        self.pushButton_20.clicked.connect(Form.copy)
        self.pushButton_21.clicked.connect(Form.copy)
        self.pushButton_22.clicked.connect(Form.copy)
        self.pushButton_23.clicked.connect(Form.copy)
        self.pushButton_24.clicked.connect(Form.copy)
        self.pushButton_25.clicked.connect(Form.copy)
        self.pushButton_26.clicked.connect(Form.copy)
        self.pushButton_27.clicked.connect(Form.copy)
        self.pushButton_28.clicked.connect(Form.copy)
        self.pushButton_29.clicked.connect(Form.copy)
        self.pushButton_30.clicked.connect(Form.copy)
        self.pushButton_31.clicked.connect(Form.copy)
        self.pushButton_32.clicked.connect(Form.copy)
        self.pushButton_33.clicked.connect(Form.copy)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "python大法好"))
        self.groupBox.setTitle(_translate("Form", "图片"))
        self.label_13.setText(_translate("Form", "TextLabel"))
        self.label_21.setText(_translate("Form", "TextLabel"))
        self.label_20.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.label_19.setText(_translate("Form", "TextLabel"))
        self.label_9.setText(_translate("Form", "TextLabel"))
        self.label_25.setText(_translate("Form", "TextLabel"))
        self.label_17.setText(_translate("Form", "TextLabel"))
        self.label_12.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.label_22.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.label_8.setText(_translate("Form", "TextLabel"))
        self.label_23.setText(_translate("Form", "TextLabel"))
        self.label_14.setText(_translate("Form", "TextLabel"))
        self.label_18.setText(_translate("Form", "TextLabel"))
        self.label_29.setText(_translate("Form", "TextLabel"))
        self.label_28.setText(_translate("Form", "TextLabel"))
        self.label_27.setText(_translate("Form", "TextLabel"))
        self.label_26.setText(_translate("Form", "TextLabel"))
        self.label_24.setText(_translate("Form", "TextLabel"))
        self.label_30.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.label_15.setText(_translate("Form", "TextLabel"))
        self.label_16.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_11.setText(_translate("Form", "TextLabel"))
        self.pushButton_29.setText(_translate("Form", "复制链接28"))
        self.pushButton_12.setText(_translate("Form", "复制链接11"))
        self.pushButton_28.setText(_translate("Form", "复制链接27"))
        self.pushButton_3.setText(_translate("Form", "复制链接2"))
        self.pushButton_13.setText(_translate("Form", "复制链接12"))
        self.pushButton_7.setText(_translate("Form", "复制链接6"))
        self.pushButton_15.setText(_translate("Form", "复制链接14"))
        self.pushButton_16.setText(_translate("Form", "复制链接15"))
        self.pushButton_30.setText(_translate("Form", "复制链接29"))
        self.pushButton_10.setText(_translate("Form", "复制链接9"))
        self.pushButton_22.setText(_translate("Form", "复制链接21"))
        self.pushButton_23.setText(_translate("Form", "复制链接22"))
        self.pushButton_21.setText(_translate("Form", "复制链接20"))
        self.pushButton_27.setText(_translate("Form", "复制链接26"))
        self.pushButton_11.setText(_translate("Form", "复制链接10"))
        self.pushButton_18.setText(_translate("Form", "复制链接17"))
        self.pushButton_26.setText(_translate("Form", "复制链接25"))
        self.pushButton_4.setText(_translate("Form", "复制链接3"))
        self.pushButton_25.setText(_translate("Form", "复制链接24"))
        self.pushButton_17.setText(_translate("Form", "复制链接16"))
        self.pushButton_2.setText(_translate("Form", "复制链接1"))
        self.pushButton_33.setText(_translate("Form", "复制链接32"))
        self.pushButton_32.setText(_translate("Form", "复制链接31"))
        self.pushButton_31.setText(_translate("Form", "复制链接30"))
        self.pushButton_20.setText(_translate("Form", "复制链接19"))
        self.pushButton_14.setText(_translate("Form", "复制链接13"))
        self.pushButton_24.setText(_translate("Form", "复制链接23"))
        self.pushButton_6.setText(_translate("Form", "复制链接5"))
        self.pushButton_5.setText(_translate("Form", "复制链接4"))
        self.pushButton_19.setText(_translate("Form", "复制链接18"))
        self.pushButton_8.setText(_translate("Form", "复制链接7"))
        self.pushButton_9.setText(_translate("Form", "复制链接8"))
        self.label_31.setText(_translate("Form", "TextLabel"))
        self.label_32.setText(_translate("Form", "TextLabel"))
        self.lineEdit.setText(_translate("Form", "123456"))
        self.label.setText(_translate("Form", "页数："))
        self.pushButton.setText(_translate("Form", "下载"))

